# Generated by Django 4.0.1 on 2022-03-28 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='currentUser',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
