# Generated by Django 4.0.1 on 2022-04-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_currentuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='message',
            name='date_added',
            field=models.TextField(),
        ),
    ]
