# Generated by Django 4.0.1 on 2022-03-06 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instagram',
        ),
    ]
