# Generated by Django 4.0.1 on 2022-03-11 11:27

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends', '0002_delete_instagram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfBirth', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('aboutMe', models.TextField()),
                ('universityName', models.CharField(max_length=100)),
                ('startYear', models.IntegerField()),
                ('endYear', models.IntegerField()),
                ('educationDesc', models.TextField()),
                ('interestDesc', models.TextField()),
                ('interestList', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
