# Generated by Django 4.0.1 on 2022-03-15 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='banner_image',
        ),
    ]
