# Generated by Django 4.0.1 on 2022-03-15 17:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0005_profile_image_profile_interestlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friendlist',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), null=True, size=20),
        ),
    ]
