# Generated by Django 4.0.1 on 2022-03-16 16:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0007_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislikedby',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), null=True, size=20),
        ),
        migrations.AddField(
            model_name='post',
            name='likedby',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), null=True, size=20),
        ),
    ]
