# Generated by Django 4.0.1 on 2022-03-26 11:05

from django.db import migrations, models
import friends.models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0008_post_dislikedby_post_likedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(null=True, upload_to=friends.models.path_and_rename),
        ),
    ]
