# Generated by Django 4.0.1 on 2022-03-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0009_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RememberList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(null=True)),
                ('friend', models.TextField(null=True)),
                ('desc', models.TextField(null=True)),
            ],
        ),
    ]
